name: song_player
description: "A Song Player that allows user to add tags on songs, and create custom playlist based on the tags filters."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audio_service: ^0.18.16
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  sqflite: ^2.4.1
  video_player: ^2.9.2
  just_audio: ^0.9.42
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true